import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import Razorpay from "razorpay";
import crypto from "crypto";
import { 
  initDb, 
  saveDb, 
  autoGenerateDaily, 
  autoGenerateWeekly, 
  autoGenerateBlog 
} from "./src/data/blogInsightsDbHelper";

dotenv.config();

const app = express();
const PORT = 3000;

// Parse JSON request bodies
app.use(express.json());

// Initialize blog and insights database on startup
const db = initDb();

// Auxiliary helper to get current Monday's date string
function getMondayStr(): string {
  const d = new Date();
  const day = d.getDay();
  // Adjust so Monday is first day
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  const monday = new Date(d.setDate(diff));
  return monday.toISOString().split("T")[0];
}

// -------------------------------------------------------------
// ASTROLOGY INSIGHTS HUB API PORTAL
// -------------------------------------------------------------

// Main query and automated generation endpoint
app.get("/api/astrology-hub", async (req, res) => {
  try {
    const todayStr = new Date().toISOString().split("T")[0];
    const currentMondayStr = getMondayStr();

    let dbUpdatesNeeded = false;

    // 1. Check if Daily Insight exists for today (active auto-generation)
    const hasTodayInsight = db.dailyInsights.some(di => di.date === todayStr);
    if (!hasTodayInsight) {
      console.log(`[Automated Hub] Daily Insight missing for today (${todayStr}). Instantiating new automated entry...`);
      try {
        const generated = await autoGenerateDaily(todayStr);
        db.dailyInsights.unshift(generated);
        dbUpdatesNeeded = true;
      } catch (err) {
        console.error("Failed to auto-generate daily content on page access:", err);
      }
    }

    // 2. Check if Weekly Forecast exists for current Monday (active weekly automation)
    const hasWeeklyForecast = db.weeklyForecasts.some(wf => wf.weekStarting === currentMondayStr);
    if (!hasWeeklyForecast) {
      console.log(`[Automated Hub] Weekly Forecast missing for current week (${currentMondayStr}). Instantiating...`);
      try {
        const generated = await autoGenerateWeekly(currentMondayStr);
        db.weeklyForecasts.unshift(generated);
        dbUpdatesNeeded = true;
      } catch (err) {
        console.error("Failed to auto-generate weekly content on page access:", err);
      }
    }

    // Save changes back to disk
    if (dbUpdatesNeeded) {
      saveDb(db);
    }

    // Return current compiled database
    res.json({
      success: true,
      dailyInsights: db.dailyInsights,
      weeklyForecasts: db.weeklyForecasts,
      blogArticles: db.blogArticles
    });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Admin API: Create / custom schedule a post
app.post("/api/astrology-hub/publish", async (req, res) => {
  try {
    const { type, payload } = req.body;

    if (!type || !payload) {
      return res.status(400).json({ success: false, error: "Type and payload parameters are required." });
    }

    const newId = `${type.substring(0, 3)}_${Date.now()}`;
    const timestamp = new Date().toISOString();

    if (type === "daily") {
      const entry = {
        id: payload.id || newId,
        date: payload.date || new Date().toISOString().split("T")[0],
        title: payload.title || "New Insights Alignment",
        summary: payload.summary || "A sudden shift in astronomical coordinates is underway.",
        content: payload.content || "Planets are moving into balanced alignments...",
        category: payload.category || "Spiritual",
        imagePrompt: payload.imagePrompt || "Golden celestial spheres",
        imageUrl: payload.imageUrl || "https://images.unsplash.com/photo-1543722530-d2c3201371e7?q=80&w=600&auto=format&fit=crop",
        isApproved: payload.hasOwnProperty("isApproved") ? payload.isApproved : true,
        publishedAt: payload.publishedAt || timestamp
      };

      // If item with same date exists, overwrite or insert
      const existingIdx = db.dailyInsights.findIndex(d => d.date === entry.date);
      if (existingIdx >= 0) {
        db.dailyInsights[existingIdx] = entry;
      } else {
        db.dailyInsights.unshift(entry);
      }
    } else if (type === "weekly") {
      const entry = {
        id: payload.id || newId,
        weekStarting: payload.weekStarting || getMondayStr(),
        title: payload.title || "Weekly Energy Roadmap",
        career: payload.career || { summary: "Steady progress predicted.", score: 85 },
        finance: payload.finance || { summary: "Evaluate portfolio channels.", score: 85 },
        relationships: payload.relationships || { summary: "Dialogue resolves blockages.", score: 85 },
        health: payload.health || { summary: "Take rests and physical hydration.", score: 85 },
        spiritual: payload.spiritual || { summary: "Meditate and pray.", score: 85 },
        imageUrl: payload.imageUrl || "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?q=80&w=600&auto=format&fit=crop",
        isApproved: payload.hasOwnProperty("isApproved") ? payload.isApproved : true,
        publishedAt: payload.publishedAt || timestamp
      };

      const existingIdx = db.weeklyForecasts.findIndex(w => w.weekStarting === entry.weekStarting);
      if (existingIdx >= 0) {
        db.weeklyForecasts[existingIdx] = entry;
      } else {
        db.weeklyForecasts.unshift(entry);
      }
    } else if (type === "blog") {
      const slug = (payload.title || "blog-article")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");

      const entry = {
        id: payload.id || newId,
        title: payload.title || "The Cosmic Code explained",
        slug: payload.slug || slug,
        excerpt: payload.excerpt || "An amazing look at astrology.",
        content: payload.content || "Vedic alignments guide us...",
        category: payload.category || "Planetary Transits",
        tags: payload.tags || ["Vedic Astrology"],
        imageUrl: payload.imageUrl || "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop",
        metaTitle: payload.metaTitle || `${payload.title || "Cosmic Code"} - pathakaanna`,
        metaDescription: payload.metaDescription || "Learn details on the latest transits.",
        isApproved: payload.hasOwnProperty("isApproved") ? payload.isApproved : true,
        publishedAt: payload.publishedAt || timestamp,
        scheduledFor: payload.scheduledFor || "",
        author: payload.author || "Pathak Aanna"
      };

      const existingIdx = db.blogArticles.findIndex(b => b.id === entry.id);
      if (existingIdx >= 0) {
        db.blogArticles[existingIdx] = entry;
      } else {
        db.blogArticles.unshift(entry);
      }
    } else {
      return res.status(400).json({ success: false, error: "Invalid content type." });
    }

    saveDb(db);
    res.json({ success: true, message: "Published successfully.", db });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// Admin API: Toggle approval status
app.post("/api/astrology-hub/toggle-approval", (req, res) => {
  try {
    const { type, id } = req.body;
    if (!type || !id) {
      return res.status(400).json({ success: false, error: "Type and id parameters are required." });
    }

    let itemFound = false;

    if (type === "daily") {
      const idx = db.dailyInsights.findIndex(i => i.id === id);
      if (idx >= 0) {
        db.dailyInsights[idx].isApproved = !db.dailyInsights[idx].isApproved;
        itemFound = true;
      }
    } else if (type === "weekly") {
      const idx = db.weeklyForecasts.findIndex(i => i.id === id);
      if (idx >= 0) {
        db.weeklyForecasts[idx].isApproved = !db.weeklyForecasts[idx].isApproved;
        itemFound = true;
      }
    } else if (type === "blog") {
      const idx = db.blogArticles.findIndex(i => i.id === id);
      if (idx >= 0) {
        db.blogArticles[idx].isApproved = !db.blogArticles[idx].isApproved;
        itemFound = true;
      }
    }

    if (!itemFound) {
      return res.status(404).json({ success: false, error: "Item not found in current record." });
    }

    saveDb(db);
    res.json({ success: true, message: "Approval state toggled successfully.", db });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// Admin API: Delete a post
app.delete("/api/astrology-hub/:type/:id", (req, res) => {
  try {
    const { type, id } = req.params;

    let itemDeleted = false;

    if (type === "daily") {
      const idx = db.dailyInsights.findIndex(i => i.id === id);
      if (idx >= 0) {
        db.dailyInsights.splice(idx, 1);
        itemDeleted = true;
      }
    } else if (type === "weekly") {
      const idx = db.weeklyForecasts.findIndex(i => i.id === id);
      if (idx >= 0) {
        db.weeklyForecasts.splice(idx, 1);
        itemDeleted = true;
      }
    } else if (type === "blog") {
      const idx = db.blogArticles.findIndex(i => i.id === id);
      if (idx >= 0) {
        db.blogArticles.splice(idx, 1);
        itemDeleted = true;
      }
    }

    if (!itemDeleted) {
      return res.status(404).json({ success: false, error: "Item not located." });
    }

    saveDb(db);
    res.json({ success: true, message: "Item deleted from records successfully.", db });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// Admin API: Directly trigger active generation using AI or templates
app.post("/api/astrology-hub/trigger-ai-generation", async (req, res) => {
  try {
    const { type, promptInput } = req.body;

    if (!type) {
      return res.status(400).json({ success: false, error: "Generation type is required." });
    }

    if (type === "daily") {
      const dateStr = promptInput || new Date().toISOString().split("T")[0];
      const generated = await autoGenerateDaily(dateStr);
      // Generate with isApproved = false initially so the Admin can review in the Admin Panel before publishing!
      // This matches requirement "Approve content before publishing"
      generated.isApproved = false;
      db.dailyInsights.unshift(generated);
      saveDb(db);
    } else if (type === "weekly") {
      const weekStr = promptInput || getMondayStr();
      const generated = await autoGenerateWeekly(weekStr);
      generated.isApproved = false;
      db.weeklyForecasts.unshift(generated);
      saveDb(db);
    } else if (type === "blog") {
      const topic = promptInput || "Zodiac Spiritual Evolution";
      const generated = await autoGenerateBlog(topic);
      generated.isApproved = false;
      db.blogArticles.unshift(generated);
      saveDb(db);
    } else {
      return res.status(400).json({ success: false, error: "Unsupported generation type." });
    }

    res.json({ success: true, message: "New draft content auto-generated and stored for your review successfully.", db });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// List of available Razorpay credential pairs in order of priority (safely trying them in sequence)
const RAZORPAY_CREDENTIALS_CHAIN = [
  {
    keyId: process.env.RAZORPAY_KEY_ID || process.env.VITE_RAZORPAY_KEY_ID || "",
    keySecret: process.env.RAZORPAY_KEY_SECRET || "",
    label: "Customer/Environment Configured Credentials"
  },
  {
    keyId: "rzp_test_SsmTMqvCYkHbGF",
    keySecret: "UXK8frxEty6EwTIOpLkhJ7uN",
    label: "Secure Workspace Core Credentials (Pair A)"
  },
  {
    keyId: "rzp_test_SsmEHFBctmppxr",
    keySecret: "hltyQIfGuKYb4dl0lqcLV3gW",
    label: "Workspace Backup Credentials (Pair B)"
  },
  {
    keyId: "rzp_test_T12Q3ZJsnLrkzT",
    keySecret: "WH3c16T5yq0nAvUlAEh2bc4F",
    label: "Workspace Alternate Credentials (Pair C)"
  }
];

// API endpoint to create standard Razorpay Order
app.post("/api/create-order", async (req, res) => {
  try {
    const { amount_inr, booking_id } = req.body;

    if (!amount_inr || isNaN(amount_inr) || amount_inr <= 0) {
      return res.status(400).json({ error: "A valid amount in INR is required to establish the transaction." });
    }

    // Convert INR to Paise (e.g. 100 INR = 10000 Paise)
    const amountInPaise = Math.round(amount_inr * 100);

    if (amountInPaise < 100) {
      return res.status(400).json({ error: "The minimum checkout amount is 100 paise (1 INR)." });
    }

    const options = {
      amount: amountInPaise,
      currency: "INR",
      receipt: `rec_${booking_id || Math.floor(100000 + Math.random() * 900000)}`,
    };

    let order = null;
    let successfulKeyId = "";
    let lastError: any = null;

    // Filter and try each set of credentials until one works or we exhaust the list
    for (const cred of RAZORPAY_CREDENTIALS_CHAIN) {
      const trimmedKey = cred.keyId.trim();
      const trimmedSecret = cred.keySecret.trim();

      if (!trimmedKey || !trimmedSecret) {
        continue;
      }

      try {
        console.log(`[create-order] Checking auth alignment with ${cred.label} - key ID: "${trimmedKey.substring(0, 15)}..."`);
        const rzp = new Razorpay({
          key_id: trimmedKey,
          key_secret: trimmedSecret
        });

        // Test if we can successfully create the order with these credentials
        order = await rzp.orders.create(options);
        successfulKeyId = trimmedKey;
        console.log(`[create-order] Success! Authenticated via ${cred.label}. Order ID: ${order.id}`);
        break; // Succesfully created order, exit sequence
      } catch (err: any) {
        console.warn(`[create-order] Credentials failed for ${cred.label}. Details:`, err.message || err);
        lastError = err;
      }
    }

    if (!order) {
      console.error("[create-order] Exhausted all fallback credentials chains. Fail state reached.");
      throw lastError || new Error("All loaded and hardcoded Razorpay credential authentication chains failed.");
    }

    return res.status(200).json({
      order_id: order.id,
      amount: order.amount,
      currency: order.currency,
      key_id: successfulKeyId // Return successfully mated key to client for checkout matching
    });
  } catch (error: any) {
    console.error("Razorpay Error (create-order) - Raw:", error);
    try {
      console.error("Razorpay Error (create-order) - Stringified:", JSON.stringify(error, null, 2));
    } catch (e) {
      console.error("Could not stringify Razorpay error:", e);
    }

    const detailedMessage = error.error?.description || error.description || error.message || "Failed to create payment order with Razorpay.";
    const detailedCode = error.error?.code || error.code || "UNKNOWN_ERROR";

    return res.status(500).json({ 
      error: detailedMessage,
      code: detailedCode,
      raw: error
    });
  }
});

// API endpoint to verify transaction authenticity via signature matching
app.post("/api/verify-payment", async (req, res) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;

    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return res.status(400).json({ error: "Missing required Razorpay signature parameters." });
    }

    // Try verifying signature with all known secrets in chain
    let verified = false;

    const secretsToTry = RAZORPAY_CREDENTIALS_CHAIN
      .map(c => c.keySecret.trim())
      .filter(Boolean);

    for (const secret of secretsToTry) {
      try {
        const hmac = crypto.createHmac("sha256", secret);
        hmac.update(`${razorpay_order_id}|${razorpay_payment_id}`);
        const generatedSignature = hmac.digest("hex");
        if (generatedSignature === razorpay_signature) {
          verified = true;
          console.log(`[verify-payment] Verification PASSED matching secret slice: "${secret.substring(0, 4)}..."`);
          break;
        }
      } catch (cryptoErr) {
        console.warn("[verify-payment] Error generating hash block: ", cryptoErr);
      }
    }

    if (verified) {
      return res.status(200).json({
        success: true,
        message: "Celestial transaction verified by secure SHA-256 signature alignment successfully."
      });
    } else {
      return res.status(400).json({
        success: false,
        error: "Signature mismatch. Authenticity verification failed."
      });
    }
  } catch (error: any) {
    console.error("Razorpay Error (verify-payment) - Raw:", error);
    try {
      console.error("Razorpay Error (verify-payment) - Stringified:", JSON.stringify(error, null, 2));
    } catch (e) {
      console.error("Could not stringify Razorpay verification error:", e);
    }
    return res.status(500).json({ 
      error: error.message || "Error processing payment signature verification.",
      raw: error
    });
  }
});

// Start Express server and integrate with Vite build-cycle
async function startServer() {
  // Vite dev server mounting or static production bundle rendering
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server listening at http://localhost:${PORT}`);
  });
}

startServer();
